# Range Function
print("Range with stop")
a = range(5)
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

print("Range with start, stop")
b = range(1, 5)
print(b[0])
print(b[1])
print(b[2])
print(b[3])

print("Range with start, stop, step")
c = range(1, 10, 2)
print(c[0])
print(c[1])
print(c[2])
print(c[3])
print(c[4])

print("Negative Range with start, stop, step")
n = range(-1, -10, -2)
print(n[0])
print(n[1])
print(n[2])
print(n[3])
print(n[4])

print("Reverse Range with start, stop, step")
r = range(5, 0, -1)
print(r[0])
print(r[1])
print(r[2])
print(r[3])
print(r[4])

